# Generated by Django 5.1.6 on 2025-03-05 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11, unique=True)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(max_length=15, unique=True)),
                ('Address', models.TextField()),
                ('DateOfBirth', models.DateField()),
                ('AadharNumber', models.CharField(max_length=12, unique=True)),
                ('PANNumber', models.CharField(max_length=10, unique=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Amex', 'Amex'), ('Rupay', 'Rupay')], max_length=15)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('credit_limit', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fixed Deposit', 'Fixed Deposit'), ('Recurring Deposit', 'Recurring Deposit')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('Home Loan', 'Home Loan'), ('Car Loan', 'Car Loan'), ('Education Loan', 'Education Loan'), ('Personal Loan', 'Personal Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_years', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
