# Generated by Django 5.1.7 on 2025-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_rename_branch_id_branch_branchid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("employee_id", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField()),
                ("accessed_module", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("access_duration", models.IntegerField()),
                (
                    "affected_customer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_extracted", models.TextField(blank=True, null=True)),
                ("transaction_details", models.TextField(blank=True, null=True)),
                ("device", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("notes", models.TextField()),
                ("risk_score", models.IntegerField()),
                ("risk_level", models.CharField(max_length=50)),
            ],
        ),
    ]
