# Generated by Django 5.1.6 on 2025-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('balance_tier', models.CharField(max_length=50)),
                ('credit_card_user', models.BooleanField(default=False)),
                ('loan_status', models.CharField(max_length=50)),
                ('relationship_tenure', models.CharField(max_length=50)),
            ],
        ),
    ]
